### ISSUE TITLE
[Subdomain Request] fnuuy.ts.md

### ISSUE THREAD

**Issue by Monsterinno** [cvyl/ts.md#5]
# Subdomain Request Form

## Your name (or alias)
            
Monster
            
## Discord (required)
            
Monster000
            
## Description of your project (required)
            
fnuuy
            
## Chosen Subdomain
            
fnuuy.ts.md
            
---
            
### Abuse of this form and subdomain will result in termination of any running services connected to your subdomain
            
- [x] I understand

**Comment by cvyl** [comment]
Issue closed as test.
